name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - run: echo "Repo: ${{ github.repository }}"

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: 'cloudrun@cs1660-spring2025-mdn29.iam.gserviceaccount.com'
          project_id: 'cs1660-spring2025-mdn29'
          workload_identity_provider: 'projects/402108316771/locations/global/workloadIdentityPools/github/providers/my-repo'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'cs1660-spring2025-mdn29'

      - name: Submit build to Cloud Build
        run: |
          gcloud builds submit --region us-central1 \
            --tag us-central1-docker.pkg.dev/cs1660-spring2025-mdn29/cloudrun/qr-attendance-app:v1

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy qr-attendance-app \
            --allow-unauthenticated \
            --image us-central1-docker.pkg.dev/cs1660-spring2025-mdn29/cloudrun/qr-attendance-app:v1 \
            --service-account cloudrun@cs1660-spring2025-mdn29.iam.gserviceaccount.com \
            --region us-central1 \
            --port 3000 \
            --platform managed \
            --quiet
